Modify script for 8GB and copy files for system and data instead of unzipping from .tbz

diff --git a/flash_all b/flash_all
--- a/flash_all
+++ b/flash_all
@@ -31,24 +31,12 @@ stop_after_kernel=false
 save_env=false
 skip_extras=false
 web=false
-url='http://download.kernelconcepts.de/~arne/odroidx/'
-flash_files="flash_all bl2.bin p4412_s_tzsw.bin u-boot.bin p4412_s_fwbl1.bin ramdisk.img u-boot.env zImage data-air.tbz data.tbz system-busybox.tbz system-root.tbz system.tbz system-touch.tbz system-latinime.tbz"
+
 
 while [ $# -gt 1 ] ; do
 	if [ "$1" = -y ] ; then
 		confirm=false
-		shift
-	elif [ "$1" = -k ] ; then
-		stop_after_kernel=true
-		flash_files="flash_all bl2.bin p4412_s_tzsw.bin u-boot.bin p4412_s_fwbl1.bin ramdisk.img u-boot.env zImage"
-		shift
-	elif [ "$1" = -w ] ; then
-		web=true
-		shift
-	elif [ "$1" = -u ] ; then
-		shift
-		url="$1"
-		shift
+		shift			
 	elif [ "$1" = -s ] ; then
 		save_env=true
 		shift
@@ -59,15 +47,6 @@ while [ $# -gt 1 ] ; do
 		break
 	fi
 done
-
-if [ "$web" = "true" -a ! -z "$url" ] ; then
-	mkdir -p /tmp/flash-sd
-	cd /tmp/flash-sd || exit 1
-	for i in $flash_files ; do
-		wget -O $i "$url/$i"
-	done
-	exec sh flash_all "$@"
-fi
 
 LTIB_PATH=$(pwd)
 
@@ -96,6 +75,7 @@ do_sync() {
 #######################################
 
 SDCARD_DEV=$1
+ANDROID_OUT=$2
 
 # Simplify the device to its minimal expression
 SDCARD_DEV="$( dirname $SDCARD_DEV )/$( basename $SDCARD_DEV )"
@@ -104,6 +84,12 @@ if [ -z $SDCARD_DEV ]; then
 	echo "ERROR: Must set the destination device\n"
 	echo "Syntax:  $0 [device]"
 	echo "Example: $0 /dev/sdg\n"
+	exit 1
+fi
+
+if [ -z $ANDROID_OUT ]; then
+	echo "ERROR: Must specify Android out/ directory\n"
+	echo "Example: $0 /home/yourname/ODROID/out/target/product/odroidu\n"
 	exit 1
 fi
 
@@ -144,10 +130,10 @@ fi
 # Copy the bootloader
 #######################################
 
-BL1_IMG=$LTIB_PATH/p4412_s_fwbl1.bin
-BL2_IMG=$LTIB_PATH/bl2.bin
+BL1_IMG=$LTIB_PATH/E4412_S.bl1.HardKernel.bin
+BL2_IMG=$LTIB_PATH/bl2.signed.bin
 BOOTLOADER_IMG=$LTIB_PATH/u-boot.bin
-TZSW_IMG=$LTIB_PATH/p4412_s_tzsw.bin
+TZSW_IMG=$LTIB_PATH/E4412_S.tzsw.signed.bin
 
 if [ -s "$BOOTLOADER_IMG" -a -s "$BL1_IMG" -a -s "$BL2_IMG" -a -s "$TZSW_IMG" ] ; then
 	echo "Copying bl1..."
@@ -198,7 +184,7 @@ fi
 # Copy the ramdisk
 #######################################
 
-RAMDISK_IMG=$LTIB_PATH/ramdisk.img
+RAMDISK_IMG=$LTIB_PATH/ramdisk-uboot.img
 
 if [ -s "$RAMDISK_IMG" ] ; then
 	echo "Copying ramdisk..."
@@ -254,7 +240,7 @@ else
 fi
 
 SIZE=`$SUDO fdisk -l ${SDCARD_DEV} 2> /dev/null | grep Disk | awk '{print $5}'`
-CYLINDERS=$( expr $SIZE / 8225280 )
+CYLINDERS=1023
 
 if [ $CYLINDERS -eq 0 ]; then
 	echo "ERROR: 0 cylinders\n"
@@ -264,34 +250,49 @@ fi
 echo "DISK SIZE - $SIZE bytes"
 echo "CYLINDERS - $CYLINDERS"
 
+
+#Disk /dev/sdf: 7888 MB, 7888437248 bytes
+#251 heads, 60 sectors/track, 1023 cylinders, total 15407104 sectors
+#Units = sectors of 1 * 512 = 512 bytes
+#Sector size (logical/physical): 512 bytes / 512 bytes
+#I/O size (minimum/optimal): 512 bytes / 512 bytes
+#Disk identifier: 0x00000000
+
+#   Device Boot      Start         End      Blocks   Id  System
+#/dev/sdf1         6716760    15270839     4277040    c  W95 FAT32 (LBA)
+#/dev/sdf2          135540     2243939     1054200   83  Linux
+#/dev/sdf3         2243940     6445679     2100870   83  Linux
+#/dev/sdf4         6445680     6716759      135540   83  Linux
+
+
 # Create a single ext3 partition while leaving space for U-Boot and kernel
 {
 	echo o
 	echo n
 	echo p
 	echo 2
-	echo 138897		# p2 start
-	echo +2237784		# p2 sectors
+	echo 135540		# p2 start
+	echo 2243939		# p2 sectors
 	echo n
 	echo p
 	echo 3
-	echo 2237785		# p3 start
-	echo +6435560		# p3 sectors
+	echo 2243940		# p3 start
+	echo 6445679		# p3 sectors
 	echo n
 	echo p
 	echo 4
-	echo 6435561		# p4 start
-	echo +6697921		# p4 sectors
+	echo 6445680		# p4 start
+	echo 6716759		# p4 sectors
 	echo n
 	echo p
-	echo 6697922		# p1 start
-	#echo +15362047		# p1 sectors
+	echo 6716760		# p1 start
+	echo 15270839		# p1 sectors
 	echo 			# p1 sectors
 	echo t
 	echo 1
 	echo c
 	echo w
-} | $SUDO fdisk -H 255 -S 63 -C $CYLINDERS ${SDCARD_DEV} >/dev/null 2>&1
+} | $SUDO fdisk -H 251 -S 60 -C $CYLINDERS ${SDCARD_DEV} >/dev/null 2>&1
 
 sleep 5
 $SUDO umount ${SDCARD_DEV}* 2> /dev/null
@@ -316,32 +317,54 @@ $SUDO mkfs.ext3 $PART_NAME_4 -L cache #> /dev/null 2>&1 || exit 1
 echo "Writing root filesystem..."
 MOUNTOPTS="-o data=writeback,noatime"
 
-#system
-mkdir -p tmp_mnt && \
+
+#mkdir -p tmp_mnt && \
+#$SUDO mount $MOUNTOPTS $PART_NAME_2 tmp_mnt && \
+#echo "installing $SYSTEM_TAR..." &&
+#( cd tmp_mnt && $SUDO tar jxf "$SYSTEM_TAR" ) && \
+#[ $skip_extras != "true" ] && for i in $LTIB_PATH/system.tbz ; do
+#	[ -f "$i" ] || continue
+#	echo "installing $i..."
+#	( cd tmp_mnt \
+#		&& $SUDO tar jxf "$i" )
+#done
+#$SUDO umount tmp_mnt
+#rmdir tmp_mnt
+
+$SUDO mkdir -p tmp_mnt && \
 $SUDO mount $MOUNTOPTS $PART_NAME_2 tmp_mnt && \
-echo "installing $SYSTEM_TAR..." &&
-( cd tmp_mnt && $SUDO tar jxf "$SYSTEM_TAR" ) && \
-[ $skip_extras != "true" ] && for i in $LTIB_PATH/system-*.tbz ; do
-	[ -f "$i" ] || continue
-	echo "installing $i..."
-	( cd tmp_mnt \
-		&& $SUDO tar jxf "$i" )
-done
-$SUDO umount tmp_mnt
-rmdir tmp_mnt
+echo "copying system and root ..." && \
+echo "changing directory ..."  && \
+cd tmp_mnt && \
+echo "copying files for root ..." && \
+$SUDO cp -r $ANDROID_OUT/root/* . && \
+echo "copying files for system ..." && \
+$SUDO cp -r $ANDROID_OUT/system/* .  && \
+cd .. && $SUDO umount tmp_mnt && $SUDO rmdir tmp_mnt
+
 
 #data
-mkdir -p tmp_mnt && \
+#mkdir -p tmp_mnt && \
+#$SUDO mount $MOUNTOPTS $PART_NAME_3 tmp_mnt && \
+#echo "installing $DATA_TAR..." &&
+#( cd tmp_mnt && $SUDO tar jxf "$DATA_TAR" ) && \
+#[ $skip_extras != "true" ] && for i in $LTIB_PATH/data.tbz ; do
+#	[ -f "$i" ] || continue
+#	echo "installing $i..."
+#	( cd tmp_mnt \
+#		&& $SUDO tar jxf "$i" )
+#done
+#$SUDO umount tmp_mnt
+#rmdir tmp_mnt
+
+
+$SUDO mkdir -p tmp_mnt && \
 $SUDO mount $MOUNTOPTS $PART_NAME_3 tmp_mnt && \
-echo "installing $DATA_TAR..." &&
-( cd tmp_mnt && $SUDO tar jxf "$DATA_TAR" ) && \
-[ $skip_extras != "true" ] && for i in $LTIB_PATH/data-*.tbz ; do
-	[ -f "$i" ] || continue
-	echo "installing $i..."
-	( cd tmp_mnt \
-		&& $SUDO tar jxf "$i" )
-done
-$SUDO umount tmp_mnt
-rmdir tmp_mnt
+echo "copying data ..." && \
+echo "changing directory ..."  && \
+cd tmp_mnt && \
+echo "copying files for data ..." && \
+$SUDO cp -r $ANDROID_OUT/data/* . && \
+cd .. && $SUDO umount tmp_mnt && $SUDO rmdir tmp_mnt
 
 do_sync
